<option value='Christ Embassy Abuja Ministry Centre'>Christ Embassy Abuja Ministry Centre</option>
<option value=' Christ Embassy Canada Region'> Christ Embassy Canada Region</option>
<option value=' Christ Embassy Eastern Europe Region '> Christ Embassy Eastern Europe Region </option>
<option value='Christ Embassy Warri Ministry Centre'>Christ Embassy Warri Ministry Centre</option>
<option value='Christ Embassy Accra Ghana Zone'>Christ Embassy Accra Ghana Zone</option>
<option value='Christ Embassy Middle East Zone/South East Asia Virtual Region'>Christ Embassy Middle East Zone/South East Asia Virtual Region</option>
<option value='Christ Embassy Port Harcourt Zone 2'>Christ Embassy Port Harcourt Zone 2</option>
<option value='Christ Embassy Abeokuta Ministry Center'>Christ Embassy Abeokuta Ministry Center</option>
<option value='Christ Embassy Ethiopia'>Christ Embassy Ethiopia</option>
<option value='Christ Embassy Ibadan South'>Christ Embassy Ibadan South</option>
<option value='Christ Embassy Owerri South East Virtual Zone 1'>Christ Embassy Owerri South East Virtual Zone 1</option>
<option value='Christ Embassy Port Harcourt Central  Zone 3'>Christ Embassy Port Harcourt Central  Zone 3</option>
<option value='Christ Embassy Port Harcourt  Ministry Centre '>Christ Embassy Port Harcourt  Ministry Centre </option>
<option value='Christ Embassy Lagos Zone 2'>Christ Embassy Lagos Zone 2</option>
<option value='Christ Embassy Lagos Zone 3'>Christ Embassy Lagos Zone 3</option>
<option value='Christ Embassy Lagos Zone 5'>Christ Embassy Lagos Zone 5</option>
<option value='Christ Embassy Lagos Zone 5'>Christ Embassy Lagos Zone 5</option>
<option value='Christ Embassy Lagos Zone 5'>Christ Embassy Lagos Zone 5</option>
<option value='Christ Embassy Lagos Virtual Zone'>Christ Embassy Lagos Virtual Zone</option>
<option value='Christ Embassy Asaba South East Virtual Zone 2'>Christ Embassy Asaba South East Virtual Zone 2</option>
<option value='Christ Embassy Calabar Ministry Center'>Christ Embassy Calabar Ministry Center</option>
<option value='Christ Embassy Lagos Zone 1'>Christ Embassy Lagos Zone 1</option>
<option value='Christ Embassy Lagos Zone 4'>Christ Embassy Lagos Zone 4</option>
<option value='Christ Embassy Port Harcourt  Zone 1'>Christ Embassy Port Harcourt  Zone 1</option>
<option value='Christ Embassy Benin Zone 1'>Christ Embassy Benin Zone 1</option>
<option value='Christ Embassy Mid West Zone'>Christ Embassy Mid West Zone</option>
<option value='Christ Embassy UK, Zone 1'>Christ Embassy UK, Zone 1</option>
<option value='Christ Embassy UK, Zone 1'>Christ Embassy UK, Zone 1</option>
<option value='Christ Embassy UK, Zone 2'>Christ Embassy UK, Zone 2</option>
<option value='Christ Embassy UK, Zone 3'>Christ Embassy UK, Zone 3</option>
<option value='Christ Embassy Onitsha Zone'>Christ Embassy Onitsha Zone</option>
<option value='Christ Embassy Southern Africa Zone 1'>Christ Embassy Southern Africa Zone 1</option>
<option value='Christ Embassy Southern Africa Zone 2'>Christ Embassy Southern Africa Zone 2</option>
<option value='Christ Embassy Southern Africa Zone 3'>Christ Embassy Southern Africa Zone 3</option>
<option value='Christ Embassy Southern Africa Zone 4'>Christ Embassy Southern Africa Zone 4</option>
<option value='Christ Embassy Sothern Africa Zone 5'>Christ Embassy Sothern Africa Zone 5</option>
<option value='Christ Embassy Houston Texas, USA'>Christ Embassy Houston Texas, USA</option>
<option value='Christ Embassy Warri Sub Zone'>Christ Embassy Warri Sub Zone</option>
<option value='Christ Embassy Kenya Zone'>Christ Embassy Kenya Zone</option>
<option value='Christ Embassy  South South   Zone 1 (Bayelsa)'>Christ Embassy  South South   Zone 1 (Bayelsa)</option>
<option value='Christ Embassy Kano Northern West Zone 2'>Christ Embassy Kano Northern West Zone 2</option>
<option value='Christ Embassy Edo North Central Zone'>Christ Embassy Edo North Central Zone</option>
<option value='Christ Embassy Nungua East West Central  Africa Zone 5'>Christ Embassy Nungua East West Central  Africa Zone 5</option>
<option value='Christ Embassy  France  Zone 2 '>Christ Embassy  France  Zone 2 </option>
<option value='Christ Embassy Douala Cameroon East Central West Africa Zone 4'>Christ Embassy Douala Cameroon East Central West Africa Zone 4</option>
<option value='Christ Embassy South South  Zone 2 (Uyo)'>Christ Embassy South South  Zone 2 (Uyo)</option>
<option value='Christ Embassy Jos North Central  Zone 1'>Christ Embassy Jos North Central  Zone 1</option>
<option value='Christ Embassy East Africa  Zone 3'>Christ Embassy East Africa  Zone 3</option>
<option value='Christ Embassy Kaduna, Northern Zone 2'>Christ Embassy Kaduna, Northern Zone 2</option>
<option value='Christ Embassy Western Europe Zone 3'>Christ Embassy Western Europe Zone 3</option>
<option value='Christ Embassy UK Zone 1 Region 2'>Christ Embassy UK Zone 1 Region 2</option>
<option value='Christ Embassy Europe  Zone 4'>Christ Embassy Europe  Zone 4</option>
<option value='Christ Embassy Yola North East  Zone 1'>Christ Embassy Yola North East  Zone 1</option>
<option value='Christ Embassy Netherlands Europe  Zone 1'>Christ Embassy Netherlands Europe  Zone 1</option>
<option value='Christ Embassy North Central Makurdi'>Christ Embassy North Central Makurdi</option>
<option value='Christ Embassy Congo DRC'>Christ Embassy Congo DRC</option>
<option value='Christ Embassy Benin  Zone 2'>Christ Embassy Benin  Zone 2</option>
<option value='Christ Embassy UK Zone 4, Region 2'>Christ Embassy UK Zone 4, Region 2</option>
<option value='Christ Embassy South West  Zone 2 (Osogbo)'>Christ Embassy South West  Zone 2 (Osogbo)</option>
<option value='Christ Embassy USA Region 1  Zone 2'>Christ Embassy USA Region 1  Zone 2</option>
<option value='Christ Embassy East West Central Africa  Zone 2 (cote d'Ivoire)'>Christ Embassy East West Central Africa  Zone 2 (cote d'Ivoire)</option>
<option value='Christ Embassy South West  Zone 3 (Abeokuta)'>Christ Embassy South West  Zone 3 (Abeokuta)</option>
<option value='Christ Embassy Abuja Zone'>Christ Embassy Abuja Zone</option>
<option value='Christ Embassy Aba Zone'>Christ Embassy Aba Zone</option>
<option value='Christ Embassy Uk  Zone 3 Region 2'>Christ Embassy Uk  Zone 3 Region 2</option>
<option value='Christ Embassy Texas Zone 1 &2'>Christ Embassy Texas Zone 1 &2</option>